### ISSUE TITLE
Academic vs. elevated access

### ISSUE THREAD

**Issue by datapumpernickel** [ropensci/rtweet#698] opened 2022-03-31 16:19 UTC
Hi all,

thanks alot for this great package. 

For lack of a better place, I am posting here, although I am aware it is not really an issue with the package. Please close or delete, if this is totally inappropriate use of the forum. 
I am currently planning a project, where I think the elevated access API would be enough. However, out of curiosity, I tried to replicate a query with the academic access API and got different results. That set off some alarms bells, as the results for a recent search should essentially be the same, when it is about a hashtag/query that most certainly does not reach the limit of tweets of the elevated access API. 

``` r
## store api keys (replace with your own keys)
api_key <- Sys.getenv("TWITTERKEY_basic_op")
api_secret_key <- Sys.getenv("TWITTERSECRET_basic_op")
access_token <- Sys.getenv("TWITTERTOKEN_basic_op")
access_token_secret <- Sys.getenv("TWITTERTOKENSECRET_basic_op")


acc_secret <- Sys.getenv('TWITTERTOKENBEARER_academic') 

## create token for querying twitter api
token <- create_token(
  app = "app_name",
  consumer_key = api_key,
  consumer_secret = api_secret_key,
  access_token = access_token,
  access_secret = access_token_secret)

tmls <- search_tweets("#windenergie -filter:retweets", n = 5000, token = token)

wind <- academictwitteR::get_all_tweets(
  q = "#windenergie",
  start_tweets = min(tmls$created_at) %>% str_replace(., " ", "T") %>% str_c(., "Z"),
  end_tweets = max(tmls$created_at) %>% str_replace(., " ", "T") %>% str_c(., "Z"),
  data_path = "test",
  bearer_token = acc_secret,
  is_retweet = F,
  n = 5000
)

missing <- wind[!wind$id %in% tmls$status_id,]
```

In this case, it is relatively few tweets that are missing, but sometimes the difference is quite large. 
Does anybody know why this is the case? 

Thanks alot in advance!

**Comment by llrs** [comment] 2022-03-31 17:55
Hi this is not a forum (in the old sense of the word), if you have questions you can post them on [discuss.ropensci.org](https://discuss.ropensci.org/) or [community.rstudio.com](https://community.rstudio.com/) I monitor and receive alerts if someone mentions rtweet there (or on rOpenSci slack)

But this might be a bug, so it is okay to ask it here. 
However, I would need to know the version of the packages (both rtweet and academictwitteR) you are using in order to reproduce your example (and even this might not be enough). When you say that some tweets are missing did you find any pattern (older tweets missing, users of some user...)?
Could you provide a list or a number of said comparison ? Such as `nrow(missing)` or/and `length(setdiff(wind$id, tmls$status_id))` and length(setdiff(tmls$status_id, wind$id))  

However, I think that the problem is that the underlying API doesn't guarantee that it returns all tweets of the query, so different queries might return different results (at least on API v1). You should check Twitter's documentation on this regard. 

I hope this helps, if you provide more information about what do you see I might be able to

**Comment by datapumpernickel** [comment] 2022-03-31 18:53
Hi! 

thanks for looking into this. Your comments already helped me further. Unfortunately, in a twist of fate, my work-computer just stopped working. So i cannot really give you the information that you are asking for. While I did look at the tweets, I could not find any systematic difference in terms of timing or users. However, I did look into the documentation and it seems that I confused v1 and v2 of the Twitter API (so much reading...) and the [documentation](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/overview) for the search function in v1 **very** clearly states: 
> Before digging in, it’s important to know that the standard search API is focused on relevance and not completeness. This means that some Tweets and users may be missing from search results.

So this is 99.9% entirely related to rtweet querying only v1. Sorry to have bugged you with this. The documentation for v2 does not mention this disclaimer, so one could assume, that this problem does not exist in v2. Once my computer is back up, I will test the v2 endpoint (with python... :O ) and see, if it returns all tweets, compared to the academic access. In that case, I think this would be a very strong argument to implement the v2 interface for rtweet. Completely understand the limitations for open source projects like this however and am thankful for what I got here. :-)

**Comment by llrs** [comment] 2022-03-31 21:10
I hope your computer gets back on.
If you want completeness using the environments (and academicTweetR) I think you can retrieve all tweets for a given search.
I'm closing this now as I think this is the root cause of the differences

Yes, I know the limitations of API v1 and it is on the roadmap, but my time is limited :)

**Closed as completed by llrs** 2022-03-31 21:10 UTC

**Comment by datapumpernickel** [comment] 2022-04-01 07:44
Just FYI: I could verify through the python library `tweepy` that indeed, as soon as I use the v2 access, recent search returns the same for a bearer token that is non-academic, as it does for an academic bearer token with get_all_tweets if the start and end time is specified to be the same. No bug with your package! 
Through a fork of  `academictwitterR` and a change in the endpoint path to recent, I am able to use the academictwitteR package without academic access! Thanks for the pointer.
