### ISSUE TITLE
`max_id` must be a character vector or data frame in search_fullarchive() function

### ISSUE THREAD

**Issue by boral** [ropensci/rtweet#578] opened 2021-05-12 15:22 UTC
### Problem

While using search_fullarchive to fetch tweets, the following error is shown : max_id must be a character vector or data frame.

### Expected behavior

No error should be generated.

### Reproduce the problem

``` r
## insert code here

df = search_fullarchive( q = '#covid place:UK OR place:GB OR place:"United Kindom"',
                        n = 500, env = 'development',
                   fromDate = "201810010000", token = token, parse = T )

```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
```
‘0.7.0.9000’

### Session info

``` r
## copy/paste output
sessionInfo()
```
sessionInfo()

**Comment by llrs** [comment] 2021-05-12 20:32
Thanks for the report! 
Sorry, I haven't set up the environment to test rtweet on fullarchive yet. This might take some time to fix. 
Could you provide what have you tried to solve it and the traceback()? It will be easier to understand what might be the problem and how to fix it. 

PS: United Kindom or United Kin**g**dom?

**Comment by Osman2004** [comment] 2021-05-29 21:59
I'm having the same issue too :(

here's the traceback():

R Under development (unstable) (2021-03-29 r80130) -- "Unsuffered Consequences"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/NewRtweet5.29/.RData]

> authapp <- rtweet_app()
Error in rtweet_app() : could not find function "rtweet_app"
> library("httr")
> library(rtweet)
> library(rtweetXtras)
> library(knitr)
> library(httpuv)
> authapp <- rtweet_app()
Error: Cancelled by user
Run `rlang::last_error()` to see where the error occurred.
> authuse <-rtweet_user()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> authapp <- rtweet_app()
> authbot <-rtweet_bot()
> dfuse2<-search_tweets("#rstats", token=authuse)
> View(dfuse2)
> View(dfuse2)
> Full_search <-search_fullarchive(q = "test", env_name = "bailapp", n=10, fromDate = "201912120000", toDate = "201912120000", token=authapp)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> library(openssl)
Linking to: OpenSSL 1.1.1j  16 Feb 2021
> Full_search <-search_fullarchive(q = "test", env_name = "bailarch", n=10, fromDate = "201912120000", toDate = "201912120000", token=authapp)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> Full_search <-search_fullarchive(q = "test", env_name = "bailsand", n=10, fromDate = "201912120000", toDate = "201912120000", token=authapp)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
>  <-rtweet_user()
Error: unexpected assignment in " <-"
> authuse <-rtweet_user()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> post_tweet("grrr hello3", token=authuse)
Your tweet has been posted!
> post_tweet("grrr hello3", token=authapp)
Error: Twitter API failed [403]
 * Your credentials do not allow access to this resource. (220)
> dfapp4<-search_tweets("#rstats", n= 20000, token=authapp)
                                                               
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", max_id=NULL, token=authapp)
Error in search_fullarchive(q = "New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform",  : 
  unused argument (max_id = NULL)
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", max_id=tweets, token=authapp)
Error in search_fullarchive(q = "New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform",  : 
  unused argument (max_id = tweets)
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", max_id=max_id, token=authapp)
Error in search_fullarchive(q = "New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform",  : 
  unused argument (max_id = max_id)
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", max_id=until_id, token=authapp)
Error in search_fullarchive(q = "New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform",  : 
  unused argument (max_id = until_id)
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
`max_id` must be a character vector or data frame
Backtrace:
 1. rtweet::search_fullarchive(...)
 2. rtweet:::search_premium(...)
 3. rtweet:::TWIT_paginate_max_id(...)
 4. rtweet::max_id(max_id)
 5. rtweet:::find_id(x, "max_id")
Run `rlang::last_trace()` to see the full context.
> 1
[1] 1
> rlang::last_trace(1)
Error in rlang::last_trace(1) : unused argument (1)
> q <-"New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform"
> tweets_bailref <-search_fullarchive(q="q", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> tweets_bailref <-search_fullarchive(q="q", n=Ing\f, env_name="bailarch", fromDate="201808010000",toDate="202007310000", max_id= token=authapp)
Error: unexpected '\\' in "tweets_bailref <-search_fullarchive(q="q", n=Ing\"
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=inf, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp)
Error in search_params(q, n = n, fromDate = format_from_to_date(fromDate),  : 
  object 'inf' not found
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=Inf, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=Inf, env_name="bailarch", fromDate="201808010000",toDate="202007310000", max_id= "max_id", token=authapp)
Error in search_fullarchive(q = "New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform",  : 
  unused argument (max_id = "max_id")
> tweets_bailref <-search_fullarchive(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=Inf, env_name="bailarch", fromDate="201808010000",toDate="202007310000", max_id= TRUE, token=authapp)
Error in search_fullarchive(q = "New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform",  : 
  unused argument (max_id = TRUE)
> tweets_bailref <-search_tweets(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=Inf, env_name="bailarch", fromDate="201808010000",toDate="202007310000",  token=authapp)
Error in vector("list", pages) : vector size cannot be infinite
> tweets_bailref <-search_tweets(q="New York bail reform OR NY bail reform OR NYC bail reform OR NYS bail reform OR New York City bail reform OR New York State bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000",  token=authapp)
> View(tweets_bailref)
> View(tweets_bailref)
> tweets_bailref <-search_tweets(q="New York bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000",  token=authapp)
> View(tweets_bailref)
> auth_setup_default(authapp)
Error in auth_setup_default(authapp) : unused argument (authapp)
> auth_setup_default()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Saving auth to '~/Library/Application Support/rtweet/default.rds'
> tweets_bailref <-search_tweets(q="New York bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000",  token=authapp)
> View(tweets_bailref)
> View(tweets_bailref)
> save_auth(authapp, "bailappr")
Error in save_auth(authapp, "bailappr") : 
  could not find function "save_auth"
> auth_save(authapp, "bailappr")
Saving auth to '~/Library/Application Support/rtweet/bailappr.rds'
> tweets_bailref <-search_tweets(q="New York bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000",  bailappr)
Error in is_character(arg) : object 'bailappr' not found
> tweets_bailref <-search_tweets(q="New York bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token= bailappr)
Error in token %||% auth_get() : object 'bailappr' not found
> tweets_bailref <-search_tweets(q="New York bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token= "bailappr")
Error: `token` is not a valid access token
Run `rlang::last_error()` to see where the error occurred.
> tweets_bailref <-search_tweets(q="New York bail reform", n=100, env_name="bailarch", fromDate="201808010000",toDate="202007310000", )
> View(tweets_bailref)
> View(tweets_bailref)
> tweets_bailref <-search_tweets(q="New York bail reform", n=inf, env_name="bailarch", fromDate="201808010000",toDate="202007310000", )
Error in TWIT_paginate_max_id(token, "/1.1/search/tweets", params, get_id = function(x) x$statuses$id_str,  : 
  object 'inf' not found
> tweets_bailref <-search_tweets(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000", )
                                                               
> View(tweets_bailref)
> View(tweets_bailref)
> auth_as("bailappr")
Reading auth from '~/Library/Application Support/rtweet/bailappr.rds'
> tweets_bailref <-search_tweets(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000", )
                                                               
> View(tweets_bailref)
> View(tweets_bailref)
> auth_setup_default()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Saving auth to '~/Library/Application Support/rtweet/default.rds'
> tweets_bailref <-search_tweets(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000", )
> View(tweets_bailref)
> View(tweets_bailref)
> tweets_bailref <-search_fullarchive(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000", )
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> tweets_bailref <-search_30day(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000")
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> tweets_bailref <-search_30day(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp, parse=T)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> traceback()
8: stop(fallback)
7: signal_abort(cnd)
6: abort(paste0("`", arg_name, "` must be a character vector or data frame"))
5: find_id(x, "max_id")
4: rtweet::max_id(max_id)
3: TWIT_paginate_max_id(token, api, params, get_id = function(x) x$statuses$id_str, 
       max_id = max_id, n = n, page_size = if (env_name == "sandbox") 100 else 500, 
       count_param = "maxResults")
2: search_premium("30day", q = q, n = n, fromDate = fromDate, toDate = toDate, 
       env_name = env_name, safedir = safedir, parse = parse, token = token)
1: search_30day(q = "New York bail reform", n = 1000, env_name = "bailarch", 
       fromDate = "201808010000", toDate = "202007310000", token = authapp, 
       parse = T)
> tweets_bailref <-search_fullarchieve(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp, parse=T)
Error in search_fullarchieve(q = "New York bail reform", n = 1000, env_name = "bailarch",  : 
  could not find function "search_fullarchieve"
> tweets_bailref <-search_fullarchive(q="New York bail reform", n=1000, env_name="bailarch", fromDate="201808010000",toDate="202007310000", token=authapp, parse=T)
Error: `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.
> traceback()
8: stop(fallback)
7: signal_abort(cnd)
6: abort(paste0("`", arg_name, "` must be a character vector or data frame"))
5: find_id(x, "max_id")
4: rtweet::max_id(max_id)
3: TWIT_paginate_max_id(token, api, params, get_id = function(x) x$statuses$id_str, 
       max_id = max_id, n = n, page_size = if (env_name == "sandbox") 100 else 500, 
       count_param = "maxResults")
2: search_premium("fullarchive", q = q, n = n, fromDate = fromDate, 
       toDate = toDate, env_name = env_name, safedir = safedir, 
       parse = parse, token = token)
1: search_fullarchive(q = "New York bail reform", n = 1000, env_name = "bailarch", 
       fromDate = "201808010000", toDate = "202007310000", token = authapp, 
       parse = T)

**Comment by Osman2004** [comment] 2021-05-29 22:19
I get the same error message :(


8: stop(fallback)
7: signal_abort(cnd)
6: abort(paste0("`", arg_name, "` must be a character vector or data frame"))
5: find_id(x, "max_id")
4: rtweet::max_id(max_id)
3: TWIT_paginate_max_id(token, api, params, get_id = function(x) x$statuses$id_str, 
       max_id = max_id, n = n, page_size = if (env_name == "sandbox") 100 else 500, 
       count_param = "maxResults")
2: search_premium("fullarchive", q = q, n = n, fromDate = fromDate, 
       toDate = toDate, env_name = env_name, safedir = safedir, 
       parse = parse, token = token)
1: search_fullarchive("New York bail reform", n = 500, fromDate = "201808010000", 
       toDate = "202007310000", env_name = "bailapp", parse = TRUE, 
       token = authapp)

**Comment by Osman2004** [comment] 2021-08-04 01:01
Just wondering if this was ever resolved?🤞🏿🙏🏿

**Comment by llrs** [comment] 2021-08-04 08:41
@Osman2004 not yet. If you submit a PR with a fix for this and I will gladly merge it.

**Comment by aterhorst** [comment] 2022-05-22 03:28
I am experiencing a similar issue with version `0.7.0.9028`. I have elevated access to the Twitter API, which does not give me access to `search_fullarchive()` but should allow me to run `search_30day()`. My syntax is:

```
auth_as("my_app") # same name as registered app

tweets30 <- search_30day(q = "advanced recycling", env_name = "my_app")
```
This query returns an error:
```
Error in `find_id()`:
! `max_id` must be a character vector or data frame
Run `rlang::last_error()` to see where the error occurred.

```
I follow the error tracing routine:

```
rlang::last_error()
<error/rlang_error>
Error in `find_id()`:
! `max_id` must be a character vector or data frame
---
Backtrace:
 1. rtweet::search_30day(q = "advanced recycling", env_name = "social_licence")
 2. rtweet:::search_premium(...)
 3. rtweet:::TWIT_paginate_max_id(...)
 4. rtweet::max_id(max_id)
 5. rtweet:::find_id(x, "max_id")
Run `rlang::last_trace()` to see the full context.


rlang::last_trace()
<error/rlang_error>
Error in `find_id()`:
! `max_id` must be a character vector or data frame
---
Backtrace:
    ▆
 1. └─rtweet::search_30day(q = "advanced recycling", env_name = "social_licence")
 2.   └─rtweet:::search_premium(...)
 3.     └─rtweet:::TWIT_paginate_max_id(...)
 4.       └─rtweet::max_id(max_id)
 5.         └─rtweet:::find_id(x, "max_id")
 6.           └─rlang::abort(paste0("`", arg_name, "` must be a character vector or data frame"))
```

**Comment by aterhorst** [comment] 2022-05-23 07:40
This problem persists in `0.7.0.9029`.

**Comment by llrs** [comment] 2022-06-18 20:01
I think I fixed both this and #713. The problem was that the premium/sandbox API v1.1 uses a different cursor to paginate results. I had to port the existing one to adapt to its changes.
It also does provide with a new extended_tweet, that had to be taken care of (It was also found on the stream API but I hadn't handled it before).

Please test the PR #716 (`remotes::install_github("ropensci/rtweet@premium")`) and let me know if this is fixed. 
I'll probably add some more examples to show how a query should be continued.

**Comment by aterhorst** [comment] 2022-06-18 23:07
Thanks heaps! I will give it a try!
________________________________

**Comment by aterhorst** [comment] 2022-06-21 06:53
It worked for a short while but now I get no content, just 43 column names. I have an extended developer license and have enabled search_30day in the sandbox. I re-tried after several hours but no joy. Not sure if there is a limit to sandbox queries.  

I had a for loop to run through three search strings. The normal ```search_tweets()``` works OK.
```
packageVersion("rtweet")
[1] ‘0.7.0.9034’

sessionInfo()

R version 4.1.3 (2022-03-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1      stringr_1.4.0      dplyr_1.0.9        purrr_0.3.4        readr_2.1.2        tidyr_1.2.0       
 [7] tibble_3.1.7       ggplot2_3.3.6      tidyverse_1.3.1    rtweet_0.7.0.9034  raster_3.5-17      sp_1.5-0          
[13] topicmodels_0.2-12

loaded via a namespace (and not attached):
 [1] progress_1.2.2    modeltools_0.2-23 tidyselect_1.1.2  terra_1.5-21      slam_0.1-50       NLP_0.2-1         haven_2.5.0      
 [8] lattice_0.20-45   colorspace_2.0-3  vctrs_0.4.1       generics_0.1.2    stats4_4.1.3      utf8_1.2.2        rlang_1.0.2      
[15] pillar_1.7.0      glue_1.6.2        withr_2.5.0       DBI_1.1.2         dbplyr_2.2.0      modelr_0.1.8      readxl_1.4.0     
[22] lifecycle_1.0.1   munsell_0.5.0     gtable_0.3.0      cellranger_1.1.0  rvest_1.0.2       codetools_0.2-18  tzdb_0.3.0       
[29] curl_4.3.2        tm_0.7-8          parallel_4.1.3    fansi_1.0.3       broom_0.8.0       Rcpp_1.0.8.3      backports_1.4.1  
[36] scales_1.2.0      jsonlite_1.8.0    fs_1.5.2          hms_1.1.1         stringi_1.7.6     grid_4.1.3        cli_3.3.0        
[43] tools_4.1.3       magrittr_2.0.3    crayon_1.5.1      pkgconfig_2.0.3   ellipsis_0.3.2    prettyunits_1.1.1 xml2_1.3.3       
[50] reprex_2.0.1      lubridate_1.8.0   rstudioapi_0.13   assertthat_0.2.1  httr_1.4.3        R6_2.5.1          compiler_4.1.3   
```

**Comment by llrs** [comment] 2022-06-21 07:37
@aterhorst I would need more information to try to find a solution to the problem you describe. Please when you report a problem provide enough information so that other developers can try the same code or very similar one to the one you used. Could you show the code used? 

You mention it worked for a short while, could you further describe what happened? Did you made 3-5 test and then it stopped or it worked you started the loop and then it stopped after 5 minutes of querying Twitter's API?

There is a rate limit to sandboxes, have you looked at the rate limit? Another option is that it could already find all the tweets for your query, I'm not sure how would rtweet or the Twitter API behave in that case

**Comment by aterhorst** [comment] 2022-06-21 10:23
Thanks. The query worked fine from start to finish the first few times but then stopped. I was refining my code so reran the same queries multiple times.

I assumed I exceeded retries but after checking the rate limits, I thought I would be able to try again after 30 minutes. No joy. We are talking about less than 20K tweets. However, it is not clear to me if there is a very limited quota for the sandbox or not. I see no evidence of my Twitter developer status being suspended.  Assume you fixed the problem and that the problem is on my end. Thanks for your help.

**Comment by llrs** [comment] 2022-06-21 10:51
Thanks for adding more information, it helps me to understand which problems may face users once released, and document and improve the package. 
 
If you have 20k tweets you made 200 requests so you had to wait if you were using the user authentication as there are rate limits per user and app:
user: 180/15 minutes
app: 450/15 minutes
Both of them at most allow 10 requests/sec and 30 requests/min (on sandbox mode), with the sandbox it doesn't allow to retrieve counts data. 
I'll haven't placed any slow down measure between requests to avoid problems with it too.

It also seems that there is a limit in the total amount of monthly tweets returned by [fullarchive 5k](https://developer.twitter.com/en/pricing/search-fullarchive) and by 30day [25k](https://developer.twitter.com/en/pricing/search-30day). It seems you'll need to wait a month as you have already requested all the free quota via the sandbox. 

I'll add this information on the documentation page of the functions.

**Comment by aterhorst** [comment] 2022-06-21 10:57
That makes sense! I have used my free quota! Thanks, heaps.

**Closed** 2022-06-27 21:59 UTC
Labels: bug, premium
