### ISSUE TITLE
search_tweets returning duplicates

### ISSUE THREAD

**Issue by ngallagher1218** [ropensci/rtweet#427] opened 2020-06-09 20:41 UTC
I looked through other issues and didn't find exactly this - apologies if I missed it. 

### Problem
I am trying to pull tweets associated with a given search term in a given hour of time using the search_tweets() function. To do this, I use a function structured as below, where I have defined SearchTerm as a character, and EarlyID and LateID as status_id numbers associated with tweets that were posted just before and just after my time window of interest. 

X <- search_tweets("SearchTerm", 
                       n = 100000,
                       type = "recent",
                       include_rts = FALSE, 
                       retryonratelimit = TRUE,
                       since_id = format(EarlyID, scientific = FALSE),
                       max_id = format(LateID, scientific = FALSE),
                       lang = "en")

This is producing duplicated rows in an unexpected way. 

### Expected behavior
I expect X to be a data frame of unique tweets. 

However, I end up with several exactly duplicated rows. That is, they're not different in terms of their number of retweets, number of likes, favorites, nothing. They are exactly duplicated rows. I can't find any explanation of this.  

### Reproduce the problem
``` r
Z <- search_tweets("LGBT", 
 n = 100000,
type = "recent",
include_rts = FALSE, 
 retryonratelimit = TRUE,
since_id = format(1270158525981962240, scientific = FALSE),
max_id = format(1270173822533197824, scientific = FALSE),
lang = "en")

```

Thanks for any guidance!! Session & rtweet information below. 

### rtweet version

rtweet version 0.7.0

### Session info

R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rtweet_0.7.0     ggcorrplot_0.1.3 forcats_0.5.0    stringr_1.4.0    dplyr_0.8.5     
 [6] purrr_0.3.4      readr_1.3.1      tidyr_1.0.3      tibble_3.0.1     ggplot2_3.3.0   
[11] tidyverse_1.3.0  psych_1.9.12.31 

loaded via a namespace (and not attached):
 [1] progress_1.2.2    tidyselect_1.0.0  haven_2.3.0       lattice_0.20-41   colorspace_1.4-1 
 [6] vctrs_0.3.0       generics_0.0.2    yaml_2.2.1        utf8_1.1.4        rlang_0.4.6      
[11] later_1.0.0       pillar_1.4.4      glue_1.4.0        withr_2.2.0       DBI_1.1.0        
[16] dbplyr_1.4.3      modelr_0.1.7      readxl_1.3.1      lifecycle_0.2.0   munsell_0.5.0    
[21] gtable_0.3.0      cellranger_1.1.0  rvest_0.3.5       httpuv_1.5.2      parallel_4.0.0   
[26] curl_4.3          fansi_0.4.1       broom_0.5.6       Rcpp_1.0.4.6      promises_1.1.0   
[31] openssl_1.4.1     scales_1.1.0      backports_1.1.6   jsonlite_1.6.1    fs_1.4.1         
[36] mnormt_1.5-7      askpass_1.1       hms_0.5.3         stringi_1.4.6     grid_4.0.0       
[41] cli_2.0.2         tools_4.0.0       magrittr_1.5      crayon_1.3.4      pkgconfig_2.0.3  
[46] ellipsis_0.3.0    prettyunits_1.1.1 xml2_1.3.2        reprex_0.3.0      lubridate_1.7.8  
[51] assertthat_0.2.1  httr_1.4.1        rstudioapi_0.11   R6_2.4.1          nlme_3.1-147     
[56] compiler_4.0.0

**Comment by llrs** [comment] 2021-02-17 22:16
With your commands I am getting 0 tweets, not sure what I should be getting. Closing as I cannot reproduce the problem at the moment. Happy to reopen the issue with more information to help debug it.

**Closed by llrs** 2021-02-17 22:16 UTC
