### ISSUE TITLE
Language filter not working on stream_tweets

### ISSUE THREAD

**Issue by rjgodard** [ropensci/rtweet#453] opened 2020-10-20 19:28 UTC
### Reproduce the problem

``` r
## insert code here

tweets <- stream_tweets(timeout = 10, token = my_token, language = "en")

```

### rtweet version

``` r
## copy/paste output
‘0.6.7’
```

### Session info

``` r
## copy/paste output
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.6.7 lavaan_0.6-7 readr_1.3.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       rstudioapi_0.11  magrittr_1.5     hms_0.5.3        MASS_7.3-51.6    mnormt_2.0.2    
 [7] pbivnorm_0.6.0   R6_2.4.1         rlang_0.4.7      fansi_0.4.1      httr_1.4.2       tools_4.0.2     
[13] tmvnsim_1.0-2    cli_2.0.2        askpass_1.1      ellipsis_0.3.1   openssl_1.4.3    assertthat_0.2.1
[19] tibble_3.0.3     lifecycle_0.2.0  crayon_1.3.4     vctrs_0.3.4      curl_4.3         glue_1.4.2      
[25] compiler_4.0.2   pillar_1.4.6     stats4_4.0.2     jsonlite_1.7.1   pkgconfig_2.0.3 
```

### Token

``` r
## copy/paste output
Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> Godard research
  key:    PWU***
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret
```

**Comment by llrs** [comment] 2021-02-18 17:32
This is a duplicate of #348. Closing this issue now  (the other one is left open) but hopefully it will get fixed soon.

**Closed by llrs** 2021-02-18 17:32 UTC
