### ISSUE TITLE
Unnecessary "Requesting token on behalf of user..."

### ISSUE THREAD

**Issue by SinaOzdemir** [ropensci/rtweet#456] opened 2020-11-05 13:52 UTC
I am trying to get the ids of an account's followers, I have a developer account and my own apps to get data. For some reason, get_followers have started to ignore my token. Any idea?

My code is:

`my_token <- create_token(app = "myapp",consumer_key = "mykey",consumer_secret = "mysecretkey",access_token ="myaccesstoken",access_secret = "mysecretaccesskey",set_renv = F)

some_account_id<-"111111111111"
rl<-rate_limits(my_token)

followers<-tibble()
cur_val<- "-1"

for ( i in 1:10){
if(isTRUE(any(rl$remaining<=0)))){
Sys.sleep(15*60)}
a<-get_followers(user = some_account_id,n = "all",retryonratelimit = F, page = cur_val,parse = T, token = mytoken)
cur_val<-next_cursor(a)
followers<-rbind(followers,a)}
`

**Comment by llrs** [comment] 2020-12-22 12:05
Can't reproduce with the the code (even after correcting the extra `)` on the condition. Probably the account used as example doesn't exists

**Comment by llrs** [comment] 2021-02-18 17:34
Closing the issue now, but if you still have it, please report it again, with more information if you can (like `traceback()`).

**Closed by llrs** 2021-02-18 17:34 UTC
Labels: authentication
