### ISSUE TITLE
lookup_coords does not work even if I enter Google API

### ISSUE THREAD

**Issue by Deena72** [ropensci/rtweet#391] opened 2020-02-06 03:24 UTC
### Problem

I was trying to collect tweets from Australia using my Twitter API

### Expected behavior

I expected to get tweets the same way as I get if I  enter USA but the data frame returns empty 
When I type lookup_coords("australia") it gives NULL. and the same applies to other countries such as Canada for example.

### Reproduce the problem

``` r
rt3 <- search_tweets(
  "lang:en", geocode = lookup_coords("australia"), apikey="my google API key", n = 100
)

```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
```

### Session info

``` r
## copy/paste output
sessionInfo()
```

### Token

``` r
## copy/paste output
rtweet::get_token()
```

**Comment by Arf9999** [comment] 2020-02-06 21:03
Have you enabled the "places" API in the Google API and enabled billing? 

See here: https://github.com/ropensci/rtweet/issues/261#issuecomment-441339524

**Comment by dieghernan** [comment] 2021-02-26 23:09
Hi,

It seems that Google API is a bit problematic (#289 , #261) . Let me share with you an alternative (see #365 @llrs ) that should work out-of-the-box. It's a rewriting of `lookup_coords` but using [Nominatim](https://nominatim.org/), that is a well-known search engine for OpenStreetMap data.

**Good news is that no API key is required** and the [Usage Policy](https://operations.osmfoundation.org/policies/nominatim/) seems to be generous for sporadic use:

> Use that is directly triggered by the end-user (for example, user searches for something) is ok, provided that your number of users is moderate

The function returns a `coords` object, as the current `lookup_coords`. A side effect is that
the internal dataset `rtweet:::citycoords` does not need to be used any more:

<details>


```r
lookup_coords_nominatim <- function(address, ...) {
  if (missing(address)) stop("must supply address", call. = FALSE)
  stopifnot(is.atomic(address))
  place <- address
  if (grepl("^us$|^usa$|^united states$|^u\\.s",
    address,
    ignore.case = TRUE
  )) {
    boxp <- c(
      sw.lng = -124.848974,
      sw.lat = 24.396308,
      ne.lng = -66.885444,
      ne.lat = 49.384358
    )
    point <- c(
      lat = 36.89,
      lng = -95.867
    )
  } else if (grepl("^world$|^all$|^globe$|^earth$",
    address,
    ignore.case = TRUE
  )) {
    boxp <- c(
      sw.lng = -180,
      sw.lat = -90,
      ne.lng = 180,
      ne.lat = 90
    )
    point <- c(
      lat = 0,
      lng = 0
    )
  } else {
    ## encode address
    address <- gsub(" ", "+", gsub(",", "", address))
    ## compose query
    params <- list(
      q = address,
      format = "json",
      limit = 1
    )
    params <- params[!vapply(params, is.null, logical(1))]
    params <- paste0(
      mapply(
        function(x, y) paste0(x, "=", y),
        names(params), params
      ),
      collapse = "&"
    )
    ## build URL - final name in English
    geourl <- paste0(
      "https://nominatim.openstreetmap.org/search?",
      params,
      "&accept-language=en"
    )
    ## read and convert to list obj
    r <- jsonlite::fromJSON(geourl)
    ## extract and name box and point data frames
    bbox <- as.double(unlist(r$boundingbox))
    boxp <- c(
      sw.lng = bbox[3],
      sw.lat = bbox[1],
      ne.lng = bbox[4],
      ne.lat = bbox[2]
    )
    point <- c(
      lat = as.double(r$lat),
      lng = as.double(r$lon)
    )
    # Full name from Nominatim
    place <- r$display_name
  }
  as.coords(place = place, box = boxp, point = point)
}

```
</details>

I added here a little reprex to check whether the function works properly or not:

<details>

``` r
# The function
library(rtweet)

lookup_coords_nominatim <- function(address, ...) {
  if (missing(address)) stop("must supply address", call. = FALSE)
  stopifnot(is.atomic(address))
  place <- address
  if (grepl("^us$|^usa$|^united states$|^u\\.s",
            address,
            ignore.case = TRUE
  )) {
    boxp <- c(
      sw.lng = -124.848974,
      sw.lat = 24.396308,
      ne.lng = -66.885444,
      ne.lat = 49.384358
    )
    point <- c(
      lat = 36.89,
      lng = -95.867
    )
  } else if (grepl("^world$|^all$|^globe$|^earth$",
                   address,
                   ignore.case = TRUE
  )) {
    boxp <- c(
      sw.lng = -180,
      sw.lat = -90,
      ne.lng = 180,
      ne.lat = 90
    )
    point <- c(
      lat = 0,
      lng = 0
    )
  } else {
    ## encode address
    address <- gsub(" ", "+", gsub(",", "", address))
    ## compose query
    params <- list(
      q = address,
      format = "json",
      limit = 1
    )
    params <- params[!vapply(params, is.null, logical(1))]
    params <- paste0(
      mapply(
        function(x, y) paste0(x, "=", y),
        names(params), params
      ),
      collapse = "&"
    )
    ## build URL - final name in English
    geourl <- paste0(
      "https://nominatim.openstreetmap.org/search?",
      params,
      "&accept-language=en"
    )
    ## read and convert to list obj
    r <- jsonlite::fromJSON(geourl)
    ## extract and name box and point data frames
    bbox <- as.double(unlist(r$boundingbox))
    boxp <- c(
      sw.lng = bbox[3],
      sw.lat = bbox[1],
      ne.lng = bbox[4],
      ne.lat = bbox[2]
    )
    point <- c(
      lat = as.double(r$lat),
      lng = as.double(r$lon)
    )
    # Full name from Nominatim
    place <- r$display_name
  }
  rtweet:::as.coords(place = place, box = boxp, point = point) # need to make this call for the repres
}

# Test againts cities - now is retrieved from an internal dataset
# Nominatim gets the info from OSM

test_city <- rtweet:::citycoords[57, ] # Just a random city

test_nominatim <- lookup_coords_nominatim(test_city$city)
test_asis <- lookup_coords(test_city$city)


class(test_nominatim) == class(test_asis)
#> [1] TRUE TRUE

test_asis
#> $place
#> [1] "bordeaux france"
#> 
#> $box
#> sw.lng.lng sw.lat.lat ne.lng.lng ne.lat.lat 
#> -0.5666667 44.7833333 -0.4666667 44.8833333 
#> 
#> $point
#>        lat        lng 
#> 44.8333333 -0.5166667 
#> 
#> attr(,"class")
#> [1] "coords" "list"
test_nominatim
#> $place
#> [1] "Bordeaux, Gironde, New Aquitaine, Metropolitan France, France"
#> 
#> $box
#>     sw.lng     sw.lat     ne.lng     ne.lat 
#> -0.6386987 44.8107826 -0.5336838 44.9161806 
#> 
#> $point
#>        lat        lng 
#> 44.8412250 -0.5800364 
#> 
#> attr(,"class")
#> [1] "coords" "list"

# Test agains actual countries

library(sf) # Spatial library
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(giscoR) # For shapes
library(dplyr) # Helper
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

cntry <- "Italy"

test_coords <- lookup_coords_nominatim(cntry)

# Convert bbox to spatial object
bbox <- test_coords$box
class(bbox) <- "bbox"

bbox <- bbox %>% st_as_sfc() %>% st_set_crs(4326)


country_sf <- gisco_get_countries(country= "italy", epsg = 4326)

par(mar=c(0,0,0,0))
plot(bbox, border = "red")
plot(st_geometry(country_sf), add = TRUE)
```


![](https://i.imgur.com/3fAeYjv.png)

<sup>Created on 2021-02-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

</details>

**Comment by dieghernan** [comment] 2021-02-26 23:25
For info, the docs of the API https://nominatim.org/api/Search/

**Comment by hadley** [comment] 2021-02-27 13:31
Closing as duplicate of #365

**Closed by hadley** 2021-02-27 13:31 UTC
Labels: documentation, location

**Comment by hadley** [comment] 2021-02-27 13:32
@dieghernan I think it would be better for rtweet to use an R package, rather than directly wrapping another API itself. That keeps rtweet focussed on the problem of the twitter API (which is already a big problem!)

**Comment by dieghernan** [comment] 2021-02-27 16:09
My main concern on that it is that it is likely that a geocoding package (added as Import, I assume) would need also to install `sf` and friends, that may be too excessive for the functionality required. Still investigating some potential candidates

**Comment by hadley** [comment] 2021-02-27 16:12
@dieghernan why would a geocoding package need to install sf?

**Comment by dieghernan** [comment] 2021-02-27 16:22
Agree, a pure API package doesn't need `sf`, but some alternatives I have seen are part of packages that handles spatial objects {osmdata}, etc. Still investigating
