### ISSUE TITLE
Support multiple tokens

### ISSUE THREAD

**Issue by llrs** [ropensci/rtweet#469] opened 2021-01-31 21:09 UTC
### Problem

If multiple tokens are present only the one selected by the enviroment variable TWITTER_PAT is used.
So users need to remember where are they stored and which one is which. 

I think a better system would be to list all the tokens available. (This way it could also warn if a new token for an existing app is being created)

To list all the tokens 

```
tk <- list.files(path = "~", pattern = ".rtweet_token*", full.names = TRUE, all.files = TRUE)
```

Also the token app name can be recovered by: `token$app$appname` so that the user can choose from which account it consumes the API calls.

**Comment by hadley** [comment] 2021-03-04 22:53
This might also be a good place to consider the problem revealed by #528 — how can we allow contributors to run "safe" calls (i.e. GETs) with their personal twitter account, without accidentally run "dangerous" calls (i.e. POSTs) that might change their account, send tweets, DMs, etc.

**Comment by hadley** [comment] 2021-03-05 13:48
Hmmmmm, maybe the tests should default to using a bearer token?

**Comment by hadley** [comment] 2021-03-05 19:24
Having spent a little time with `bearer_token()` I think it might be worth a holistic review of authentication. I think there are three main forms of authentication:

* app: collecting data
* user: casual user, take actions on behalf of user
* bot: take actions on behalf of app

And each uses a slightly different set of data from the "keys and tokens" page:

* app: bearer token
* user: api key & secret (+ interactive user auth)
* bot: api key & secret, access token & secret

<img width="451" alt="Screenshot 2021-03-05 at 1 00 46 PM" src="https://user-images.githubusercontent.com/4196/110163592-da4d8c80-7db5-11eb-8dc3-2aaff9a02335.png">

The only scenario that requires caching is "user", because the interactive auth generates a couple of pieces of data that we want to preserve over time. But all scenarios want to be able to change the default token for the session. I wonder if it might be better to set up the auth around these these scenarios:

* `auth_app(bearer)`
* `auth_user(api_key, api_secret)`
* `auth_bot(api_key, api_secret, access_key, access_secret)`

And then provide some way to set the default token. We'd still use caching for the default user token, but for anything else you'd call the appropriate auth function and then set the default:

```R
auth_set_default(auth_app("AXACSFASDFA--332342"))
auth_set_default(auth_bot(...))
auth_set_default(loadRDS("my-cache.Rds"))
```

@llrs do you think that would cover for your use case?

**Comment by llrs** [comment] 2021-03-05 20:42
I have a bot and my own account has also developer access and an app associated with it. Sometimes I had to post from the bot as I ran the code on my computer instead of on Github Actions and I didn't want to use my personal app authentication (maybe I shouldn't use have it and rely only on the default app?). 
I want to have cached all these apps so I do not need to have a *.txt file with those tokens around on the computer to be copied.
Under the new scheme if I am using my personal account on twitter and want to post as another user (not the bot) what `auth_` method should I use?

**Comment by hadley** [comment] 2021-03-05 21:01
If you want a script to post as your user, I'm proposing that you'd do:

```R
# once
token <- auth_user(...)
saveRDS(token, "my-token.rds")

# every time in the future
auth_set_default(readRDS("my-token.rds"))
```

We could automate this a little bit, but I like the idea that you are explicitly in charge of managing the token; there's no magic about where it's stored or how it's loaded.

For the bot case, I think you'd save the various bits as env vars and do

```R
auth_set_default(auth_bot(Sys.getenv("MY_APP_SECRET"), ..))
```

That seems like an annoying amount of typing, so maybe we could add a helper like

```R
auth_set_default(auth_bot(from_env_vars = "MY_APP"))
```

**Comment by llrs** [comment] 2021-03-05 21:18
I would prefer to use `get_tokens()` and be presented with a list of tokens available (displaying only appname used to store them) and select from there (and provide an argument to select it directly based on the app name). If none exists then use the `default_token()`. This way we could also help existing users to move to the new rtweet by checking and moving their already stored token and check if they are adding a new app token or overwriting one. 
The whole idea of using tokens and appdirs is to not have environment variables on .Renviron your last lines go in the other direction (although.

**Comment by hadley** [comment] 2021-03-05 22:05
I can't quite see how that would work — you can't identify tokens just by their app name because some bearer tokens don't need to store the app name, and user tokens need to be identified by a combination of app name and user name. 

It also makes me slightly uneasy to store all of the tokens in a very obvious global place; if you're using a bot token in one app, I think it makes more sense to keep it scoped to that one app, rather than in a global location. That also makes the deployment story much easier — if you want to a script unattended on another machine (e.g. GHA) you can use exactly the same code without having to worry about how to get the token out of the cache directory and on to another computer.

**Comment by hadley** [comment] 2021-03-06 14:31
Last night, I realised that if you want to cache a token locally, a pretty obvious snippet would be something like this:

```R
if (!file.exists("my-token.rds")) {
  token <- auth_user(...)
  saveRDS(token, "my-token.rds")
} else {
  token <- readRDS("my-token.rds")
}

auth_set_default(token)
```

And that's going to be a pretty common pattern, so it might be worth wrapping it up in to a function:

```R
use_local_token("my-token", auth_user(...))
#> Reading token from 'my-token.rds'
```

Then we could pair it with a function that saves in the global cache:

```R
use_global_token("my-token", auth_user(...))
#> Reading token from '~/Library/Caches/rtweet/my-token.rds'
```

That would give users the choice of where to store the token — they can store it globally to easily share across projects or store it locally to easily deploy a project to another computer.

Note that the second argument would be optional, so you could have a secure script stored elsewhere that set up all the tokens you use across projects:

```R
use_global_token("my-token")
#> Error: No rtweet token called `my-token` found.
#> Call `create_global_token()` to create
```

(I think it's important that script exist somewhere for reproducibility; you do want to record somewhere exactly what app you want to use for each project.)

And then the first call to `get_token()` could remind you of the options:

```R
t <- get_token() 
#> Reading token from '~/Library/Caches/rtweet/defaul.rds'
#> * Call `use_global_token()` to use a shared token
#> * Call `use_local_token()` to use a project-specific token
#> * Call `use_global_token("default")` to suppress this message
```

What do you think of this idea?

---

I also realised that I forgot to explain my new understanding of bearer tokens — I now really think the right way to specify them is to allow the user to copy and paste the bearer token from their app dashboard. The benefit of this is that the bearer token is easily changed —so if you accidentally expose the bearer token, you can click the regenerate button on the app dashboard, and the old token instantly stops working. The bearer token is still equivalent to a user name + password, so its not a good idea to specify inside a script and you'd still want to use `use_global_token()`.

**Comment by hadley** [comment] 2021-03-06 14:39
One last thought — regardless of what interface we implement we should provide an `rtweet_sitrep()` function that would tell you which token is currently the default, what sort of token it is (bearer, app, or bot), and what permissions it has (read, write, dm, etc).

**Comment by llrs** [comment] 2021-03-08 19:14
I think that one thing is that some auth do not need to store app_name an another what is more convenient for the user. From my experience having several tokens created by rtweet and not knowing which one is which lead to a lot of confusion (I am currently at .rtweet_token13.rds and don't know which of the 12 previously was for the same application). So, for user convenience would like to know what application token is being stored.

Not sure what it can be done with the bearer token and what with the access token & secret. But to obtain them the user must apply to have a developer access so from the user point of view is almost the same difficulty. 

I am not sure what scoping do you suggest, and how having tokens all around instead in one place will be easier for a user. Yest it might be riskier to have all the tokens in a single place, but currently it is also risky to have it at $HOME. For my bot, I just recreate the token on each GHA, so it doesn't really matter where it is stored, but on my computer it does. Having a local token for a project that it is not under the project directory will complicate the code and the precautions users must follow, in my opinion (git, copy and paste). I think it makes more sense to have the token in a central place, not that so many people have several application on Twitter. Those in need to share a project with others will be able to do so without sharing the token unless they specifically need so. 

I think usually the user will want to cache the token, so the default set_renv/cahce = TRUE`, makes sense.
Functionality similar to `auth_set_default` you propose is what I had in might for `get_tokens`:

```r
get_tokens() {
  tk <- list.files(path = token_cache_path(), pattern = ".RDS*", full.names = TRUE, all.files = TRUE)
  if (length(tk) == 0) {
    .state$token <- default_token()
  }
  select(tk)
}

token <- get_tokens()
#> Select token to use:
#> 0: none
#> 1: rtweet2rstats
#> 2: my_personal_app
#> 3: my_work_related_app
```

These tokens/ might be the bearer token, the default or with the access token & secret, but to the user it is important to know what they are about (and this is reminded by the appname). 
Or if it is the first time and no tokens exists:

```r
token <- get_tokens()
#> Error: No rtweet token called `my-token` found.
#> Call `create_token()` to create one
```

I like the idea of rtweet_sitrep() but not sure how/when would users use it? When starting a project? Before running some code with Twitter calls via rtweet?

**Comment by hadley** [comment] 2021-03-08 20:08
I think it's reasonable to default to storing tokens in the global cache directory if you think that's the most common use case, and I think your interface for `get_tokens()` is the right approach

However, I really don't think it's a good idea to cache tokens by default — that feels risky to me, because you're saving confidential information without explicit user confirmation. It's not much extra work for the user to deliberately say they want to cache a token (and they'd need to provide a name anyway), and it adds an extra layer of security.

Would you mind expanding a bit on how you see people adding tokens to the cache?

**Comment by hadley** [comment] 2021-03-08 21:49
(Also I do think we should deprecate `get_token()` in favour of `token_load_from_cache()` or similar, since all the other functions get data from the twitter API)

**Comment by alexpghayes** [comment] 2021-03-08 22:02
Related request while this is under consideration: I have a Twitter project where I would like to use both `auth_app(bearer)` and `auth_user(api_key, api_secret)` for data collection at the same time (both tokens from the same project). It would be nice to be able to use both tokens at once to pull data faster. At one point @mkearney was working on this is in a separate repo, but it would be nice to just have this in `rtweet` if there's a big auth overhaul.

**Comment by hadley** [comment] 2021-03-08 23:53
@alexpghayes I think that is out of scope for rtweet; you can always supply a manual `token` — otherwise I don't think rtweet should do anything that feels like it's working around twitter's rate limits.

**Comment by llrs** [comment] 2021-03-09 00:20
Ok, we can change the cache to default FALSE. 

```r
auth_user <- function(..., appname, cache= FALSE {
    ....
    if (cache) {
      file <- paste0(rtweet_cache_path(), "/", appname, ".RDS")
      if (file.exists(file)) {
            # Add new information to token
            # Could be a new helper function
      }
      saveRDS(token, file)
    }
}
```
 and all of them to the same place. 

About the names, I agree that we need to find a better way to name functions. But despite this being a major version change I think we will be breaking too much: function names, loading token, where it is stored... I worry many scripts will break. 

@alexpghayes Doesn't it count for the same api rate limits? What do you mean with pull the data faster?
I mean the current idea is for juggling with several apps/accounts (that's also a reason to only save by appname).

**Comment by alexpghayes** [comment] 2021-03-09 17:08
Currently, to my understanding, `rtweet` does not allow users to save a bearer token, but instead requests a bearer token on behalf of the user via the generation steps described at https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens. 

`v2` endpoints need a bearer token and it would be nice for users to just drop the token they generate from the Twitter developer interface into some sort of auth/token caching.

I cannot tell if my understanding of the current `bearer_token()` is somehow incorrect or if `bearer_token()` itself just doesn't work. Running into this as I start to work on `v2` endpoints.

**Comment by hadley** [comment] 2021-03-09 17:45
IMO is `bearer_token()` is currently incorrect, so we'd add a `auth_app(bearer)` (and probably `auth_bot()`) to complete `auth_user()` shown above.

**Comment by llrs** [comment] 2021-03-11 18:06
So first call creating a token `auth_user(..., cache = "appname_whatever")`

Next session
```r
token <- get_tokens()
#> Select token to use:
#> 0: none
#> 1: rtweet2rstats
#> 2: my_personal_app
#> 3: appname_whatever
post_tweet("my second tweet #rstats", token = token)
```
Or in the following sessions:

```r
use_token("appname_whatever")
post_tweet("my second tweet #rstats")
```

Where use_token is something very similar to `get_tokens()` could be the same function:

```r
use_token <- function(cache, path = NULL)
  if (!is.null(path)) {
      path <- token_cache_path()
  }
  path <- paste0(path, "/", cache, ".rds")
  if (file.exists(path) {
    .state$token <- readRDS(path)
    return()
  }
 warning("cache ", cache, "not found using default token.")
 .state$token <- default_token()
}
```

**Comment by hadley** [comment] 2021-03-21 14:09
How about instead of `use_token()` we call it `use_auth()`? Then you'd have the family of auth functions:

```R
auth_app(bearer)
auth_user(api_key, api_secret)
auth_bot(api_key, api_secret, access_key, access_secret)

use_auth()
```

As you suggest, `use_auth()` (with no arguments) would `ls` the cache directory and offer a menu of options (or error, if you're in a non-interactive environment)).

I still think it would be better to have an explicit save action so that you'd do:

```R
save_auth("appname_whatever", auth_user(...))
# new session
use_auth("appname_whatever")
```

Otherwise you have to entangle the creation and caching of credentials, which IMO makes the design a little inelegant and a little harder to reason about.

**Comment by llrs** [comment] 2021-03-22 12:53
Yes, better name, as it combines well with each auth functions.
Also I agree on having an explicit save action. 

You had started working on the authentication (#530, #529 ) and I think this affected them. Will you send a PR with these changes or do you prefer me to make a PR about this (first/later?) ?

**Comment by hadley** [comment] 2021-03-22 13:11
I'm happy to do a PR.

**Comment by hadley** [comment] 2021-03-23 21:51
What do we want to happen the first time that someone uses rtweet? (i.e. there are 0 saved tokens). Should it error and tell you to run `save_auth(auth_user(), "default")` or should it do it for you?

**Comment by llrs** [comment] 2021-03-24 08:24
If this is an interactive session save it (to keep the same behavior to users). If not interactive do not save the token (bots on GHA wouldn't need to saved it only use on that session).

**Comment by hadley** [comment] 2021-03-24 12:03
It's going to fail in an non-interactive session anyway, because there's no way to do the interactive auth flow.

**Comment by hadley** [comment] 2021-03-24 12:56
Now that I've started writing this I don't love that auth sometimes appears as a prefix (for the auth types) and sometimes appears as a suffix (for the auth actions):

```R
auth_app()
auth_user()
auth_bot()
use_auth()
save_auth()
get_auth()
```

Maybe it would be better to consistently use a prefix, making a sub-prefix for the auth types:


```R
auth_type_app()
auth_type_user()
auth_type_bot()
auth_use()
auth_save()
auth_get()
````

(I'm not sure `auth_get()` should be exported but it seems annoying not to have some way to see what the current auth mode is)

**Comment by llrs** [comment] 2021-03-24 13:49
I don't like the sub-prefix, I would prefer to have auth_app. I think it is implicit with `app/user/bot` that they are a type of authentication.

**Comment by hadley** [comment] 2021-03-24 13:51
Just to be clear, you're suggesting this?

```R
auth_app()
auth_user()
auth_bot()
auth_use()
auth_save()
auth_get()
```

**Comment by llrs** [comment] 2021-03-24 13:58
Yes. I don't see any problem with use/save/get/_auth as this differentiate between creating a token and doing something with it, but if you want to have it all starting the same way then a shorter and easier  to disambiguate.

**Comment by jennybc** [comment] 2021-03-24 20:18
How about:

``` r
auth_as_app()
auth_as_user()
auth_as_bot()
```

for the functions that initiate auth or put a token into force? Or `auth_with_*()`?

As an outsider / newcomer, I would probably assume that `auth_app()` reveals the current oauth app and `auth_user()` reveals the currently authenticated user. And it looks like I would be wrong about that.

**Comment by llrs** [comment] 2021-03-24 20:26
Short and clear, I like it. Thanks for the suggestion!

**Comment by jennybc** [comment] 2021-03-24 22:21
A slightly refined proposal, now that I've absorbed a bit more about Titter auth. Maybe something like:

```
auth_as(rtweet_user())
auth_as(rtweet_bot())
auth_as(rtweet_app())
```

**Comment by hadley** [comment] 2021-03-24 22:25
I like it!

**Closed** 2021-03-30 11:54 UTC
Labels: enhancement
