### ISSUE TITLE
Importing bookmarked tweets

### ISSUE THREAD

**Issue by esanfar** [ropensci/rtweet#344] opened 2019-07-20 03:59 UTC
I looked for a function to import own account bookmarks and I couldn't find anything. Bookmarking tweets was not universally available, but it is now, and it would be great to be able to import tweets saved in it.

**Comment by Arf9999** [comment] 2019-07-20 09:27
There doesn't seem to be a Twitter API endpoint for bookmarks (yet?) https://developer.twitter.com/en/docs/api-reference-index

**Comment by llrs** [comment] 2021-02-16 22:10
Still not available. Apparently it is something that twitter don't want to expose. Closing the issue, if they make it available open an issue again please

**Comment by tchakravarty** [comment] 2022-06-22 13:57
Hi,

This seems to now be available: https://twittercommunity.com/t/build-with-bookmarks-on-the-twitter-api-v2/168804.

It would be great if `rtweet` exposed a `get_bookmarks` function based on this. 

Thanks.

**Comment by rbcavanaugh** [comment] 2022-11-11 14:51
Any chance of some movement on this? Would love to be able to pull all of my bookmarks before twitter completely implodes. Thanks!

**Comment by Arf9999** [comment] 2022-11-11 14:59
If you pull your archive from Twitter via the web site, you should be able to parse the bookmarks and lookup the statuses via rtweet. Not a single step, but should deliver the results that you need.
________________________________

**Comment by llrs** [comment] 2022-11-11 15:38
@rbcavanaugh Yes, I am working on supporting API v2 but I had started by the streaming API which I thought would stop working last week. 

The initial support for API v2 is already present in the devel branch but it is still not yet fully functional to be released (it doesn't have support for extensions and fields yet). If you want you can start a PR and I can help with it (you are not the first person to ask for it).

**Comment by llrs** [comment] 2022-11-14 22:02
Mmh, yes I checked my own archive and it didn't even contain a reference to saved or bookmarked tweets. Sorry, I'll up this in the list of endpoints to provide support soon. However, the API requires a different authentication method for this endpoint, so existing code for API v2 doesn't work (I hoped it would).

**Comment by llrs** [comment] 2022-11-20 12:32
I add here an app to retrieve all bookmarked tweets https://twitter-bookmarks-exporter.herokuapp.com/. It provides with a webpage with links to all the bookmarked tweets (and contents referenced there). Note it might take a long time to retrieve all the content.  
Thanks @adriaaula for mentioning it.

**Comment by Lextuga007** [comment] 2022-11-25 17:49
I've just used the app to get 289 links and it was really fast! Thanks for building and sharing @llrs

**Comment by deborahapthorp** [comment] 2022-12-06 05:43
Thanks, but I couldn't get that app to work at all - is there a newer version?

**Comment by mpettis** [comment] 2022-12-09 15:36
I get an Application Error on the herokuapp above, to confirm what I think @deborahapthorp is saying as well.

**Comment by llrs** [comment] 2023-01-28 22:52
Good news! I think I figured out the problem with the authentication method required for this (and others endpoints). It needs more testing and I need to understand more about it: if it will work with the current default token provided by rtweet (it doesn't seem to), and why it fails after some time using it (I think this is Twitter's fault as other tokens that did work also stopped working). 
But in the devel branch (version 1.1.0.9002) there is a function to retrieve them! Hopefully next release (If I'm lucky next month) you will be able to download them. 

However, [the endpoint](https://developer.twitter.com/en/docs/twitter-api/tweets/bookmarks/api-reference/get-users-id-bookmarks) only returns the "Allows you to get an authenticated user's 800 most recent bookmarked Tweets." So if we'll get all or not (while testing it seemed at one point like it could continue to the next page above the 800 tweets).

**Comment by llrs** [comment] 2023-02-02 11:59
Given that Twitter won't be free to download bookmarks next week (See announcement: https://twitter.com/TwitterDev/status/1621026986784337922) I recommend to extract the downloads with the code as is: 

```
devtools::install_github("ropensci/rtweet@devel")
library("rtweet")
token <- rtweet_oauth2() # You'll need to provide the id and secret of your app.
ub <- user_bookmarks("123456789") # ID
saveRDS(ub, "my_bookmarks.RDS")
```

The authentication mechanism might not work, if it does, it will be for only 2 hours. 
I'm reconsidering the future of the package and my investment in it, but [I'll keep monitoring and post](https://twitter.com/Lluis_Revilla/status/1621037116334477312) more as the changes develop.

**Comment by adriaaula** [comment] 2023-02-02 12:03
Thanks a ton for the code snippet Lluis! 
It's disappointing to say the least, and it adds up more pressure to go somewhere else, let's hope I have enough pressure to go now haha

**Comment by Lextuga007** [comment] 2023-02-02 12:03
Yes, echo that, thanks for the tip off that it's going to charge soon. Much appreciated!

**Comment by bassamsdata** [comment] 2023-02-03 16:20
> The authentication mechanism might not work, if it does, it will be for only 2 hours.
> I'm reconsidering the future of the package and my investment in it, but [I'll keep monitoring and post](https://twitter.com/Lluis_Revilla/status/1621037116334477312) more as the changes develop.
Thank you so much for all the support and effort you put in this package.

unfortunately, The message always appears when I try to do anything, the error message appears when `token_oa2 <- rtweet:::rtweet_oauth2() ` even though I provided the id and secret.

is there a way to export the bookmarks 🫣. note: I used to authenticate using the default in the browser.

<img width="561" alt="Screen Shot 2023-02-03 at 11 13 17 AM" src="https://user-images.githubusercontent.com/105807570/216652470-2efcf7f7-d70a-48dd-9721-942625ff7ce3.png">


<img width="595" alt="Screen Shot 2023-02-03 at 11 15 53 AM" src="https://user-images.githubusercontent.com/105807570/216652906-99a6e368-d417-42e5-b75c-4bcb8612039f.png">


<img width="577" alt="Screen Shot 2023-02-03 at 11 16 01 AM" src="https://user-images.githubusercontent.com/105807570/216652920-39776602-17ce-41ee-9399-2870ba07ca49.png">

**Comment by mpettis** [comment] 2023-02-03 16:26
@llrs I completely understand your question to further support of this package.  I appreciate your work to this point, and will just say my use case is to just extract meaningful history from Twitter before I stop using it altogether.  Thanks for the work I've used!

**Comment by bassamsdata** [comment] 2023-02-03 16:38
> unfortunately, The message always appears when I try to do anything, the error message appears when `token_oa2 <- rtweet:::rtweet_oauth2() ` even though I provided the id and secret.

I just want to update on my comment that after removing the `s` from `https://127.0.0.1:1410/` I wan able to authenticate yet another problem appeared when doing `ub <- rtweet:::user_bookmarks("123456789", parse = FALSE, n = Inf, token = token_oa2)`
<img width="521" alt="Screen Shot 2023-02-03 at 11 34 47 AM" src="https://user-images.githubusercontent.com/105807570/216657366-b72d692b-7deb-4a8e-8e2e-12ff031c5149.png">

I have the last verion of `httr2` and the last version of `rtweet@devel`.

Thanks a lot

**Comment by llrs** [comment] 2023-02-03 17:03
@bassamsdata  Did you replace 123456789 by your own Twitter id?

**Comment by bassamsdata** [comment] 2023-02-03 17:05
> @bassamsdata Did you replace 123456789 by your own Twitter id?

yea absolutely  :)

**Comment by llrs** [comment] 2023-02-03 17:14
I'll need more information to try to help you. What is the token_oa2 output? What is the client output? What did you try?

**Comment by bassamsdata** [comment] 2023-02-03 17:30
Thanks for you help, I'm just trying to download my book marks. they are around 500 to 600.

`token_oa2` output:
<img width="602" alt="Screen Shot 2023-02-03 at 12 17 16 PM" src="https://user-images.githubusercontent.com/105807570/216666166-7267f71f-d241-43cf-8e62-17348d82d973.png">

`rtweet:::rtweet_client()` output with client id and client secret
<img width="458" alt="Screen Shot 2023-02-03 at 12 18 22 PM" src="https://user-images.githubusercontent.com/105807570/216666579-26d2a7dd-de93-4bc1-b8b8-dab0c46b6be4.png">

no output for this `rtweet:::client_as(client)`

output for this `token_oa2 <- rtweet:::rtweet_oauth2()`
<img width="547" alt="Screen Shot 2023-02-03 at 12 21 23 PM" src="https://user-images.githubusercontent.com/105807570/216668677-69137049-58a1-4232-9b21-c64e30992e6a.png">


so I added client manually `token_oa2 <- rtweet:::rtweet_oauth2(client = client)`
and the output is to open the browser and authorize. I did authorize, 
<img width="677" alt="Screen Shot 2023-02-03 at 12 25 51 PM" src="https://user-images.githubusercontent.com/105807570/216667911-3ac2b0ea-542e-4ec9-aeb6-b6912cd7ceeb.png">


and checked the app inside the twitter settings.
![image](https://user-images.githubusercontent.com/105807570/216667506-98995c94-64ea-4ae8-9920-c53cbf477cd7.png)


then when I try to download my bookmarks, it shows this error:
<img width="805" alt="Screen Shot 2023-02-03 at 12 27 22 PM" src="https://user-images.githubusercontent.com/105807570/216668115-0e5b3208-9f71-4028-80e5-62eea8830e9f.png">

just to note: if i did something like this `useRs <- search_users("#tidytuesday", n = 100)` it works.

**Comment by llrs** [comment] 2023-02-04 08:58
@bassamsdata Please next time post text instead of images, it is easier to search and copy to the terminal. 
It would be helpful to know the id of your client (and without the secret I cannot do anything). It would help me verify if you used the default client or not. If you used the default client it won't work.
The `search_users` used a different token for the requests. It wasn't used to make the requests, you should have used `search_users("#tidytuesday", n = 100, token = token_oa2)`. The OAuth2 token is only valid in some endpoints of the the API v2 not in the v1.

**Comment by bassamsdata** [comment] 2023-02-04 16:18
> Please next time post text instead of images, it is easier to search and copy to the terminal.

My bad, sorry.

>It would be helpful to know the id of your client

```r
client <- rtweet:::rtweet_client(client_id = "dWJSZXljQ2NSQkNlNFFlc3lNZm86MTpjaQ",
                                 client_secret = )
<httr2_oauth_client>
name: rtweet
id: dWJSZXljQ2NSQkNlNFFlc3lNZm86MTpjaQ
secret: <REDACTED>
token_url: https://api.twitter.com/2/oauth2/token
auth: oauth_client_req_auth_header
```
> If you used the default client it won't work.

I used the twitter provided client.

> The search_users used a different token for the requests

```r
> search_users("#tidytuesday", n = 100, token = token_oa2)
Error in `check_token()`:
! `token` is not a valid access token
Run `rlang::last_error()` to see where the error occurred.
```

the output of `client` and `token_oa2`
```r
> client
<httr2_oauth_client>
name: rtweet
id: dWJSZXljQ2NSQkNlNFFlc3lNZm86MTpjaQ
secret: <REDACTED>
token_url: https://api.twitter.com/2/oauth2/token
auth: oauth_client_req_auth_header

> token_oa2
<httr2_token>
token_type: bearer
access_token: <REDACTED>
expires_at: 2023-02-04 12:59:07
refresh_token: <REDACTED>
scope: mute.write tweet.moderate.write block.read follows.read offline.access list.write bookmark.read list.read tweet.write space.read
block.write like.write like.read users.read tweet.read bookmark.write mute.read follows.write
```

here is the output of the` user_bookmarks`
```r
> ub <- rtweet:::user_bookmarks("bassamstreet", parse = FALSE, n = Inf, token = token_oa2)
Error in `resp_abort()`:
! HTTP 401 Unauthorized.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by llrs** [comment] 2023-02-06 09:06
I haven't heard complains from any other users (after last update of the sample code), I don't know for sure what might be the cause. It could be that your app is not authorized for API v2 and you might need to refresh the authorization or select a different type of APP in the developer.twitter.com menu, but using `http://127.0.0.1:1410/` for confirming the app is fixed in rtweet code.

**Comment by llrs** [comment] 2023-02-25 23:46
@bassamsdata Rechecking your code, I realize now that you were using you twitter name, not your id with numbers. I've added a check to detect those kind of errors.

I'm closing the issue now, as I've made `user_bookmarks` to be exported (for next release). 

```r
devtools::install_github("ropensci/rtweet@devel")
library("rtweet")
client <- rtweet_client() # You'll need to provide the id and secret of your app.
client_as(client)
token_oa2 <- rtweet_oauth2() 
ub <- user_bookmarks("123456789", 
                     expansion = NA, fields = NA, # To export everything: alt text, images, urls, ...
                     parse = FALSE, n = Inf, token = token_oa2)
saveRDS(ub, "my_bookmarks.RDS")
```

**Closed by llrs** 2023-02-25 23:46 UTC
Labels: enhancement, API v2
