### ISSUE TITLE
stream_tweets returns NULL

### ISSUE THREAD

**Issue by sometimesabird** [ropensci/rtweet#714] opened 2022-06-01 05:02 UTC
### Problem

The issue appears to be similar to the ones encountered in a couple of posts here and elsewhere online, usually considered non-reproducible.

_stream_tweets_ returns value NULL, despite correct authentication. If directed into a json file, the file contains a bunch of lines with "HTTP ERROR: Problem accessing '/1.1/statuses/sample.json'. Please use V2 filtered and sample volume stream as alternatives".

I report this for my Linux computer, but the same thing happens on an iMac.

### Expected behavior
Should be returning the stream.

### Reproduce the problem

Setting up:
``` r
library(rtweet, tidyverse)
app <- 'XXXX'
consumer_key <- 'XXXX'
consumer_secret <- 'XXXXX'
access_token <- 'XXXXXX'
access_secret <- 'XXXXX'
token <- create_token(app = app, 
                      consumer_key = consumer_key, 
                      consumer_secret = consumer_secret, 
                      access_token = access_token, 
                      access_secret = access_secret)
```

Check that authentication works:
``` r
> search_tweets("#rstats", n = 1, include_rts = FALSE, token = token)
# A tibble: 1 × 90
  user_id   status_id created_at          screen_name text  source
  <chr>     <chr>     <dttm>              <chr>       <chr> <chr> 
1 12964800… 15318608… 2022-06-01 04:51:06 DataScienc… Kend… Reviv…
# … with 84 more variables: display_text_width <dbl>,
#   reply_to_status_id <lgl>, reply_to_user_id <lgl>,
#   reply_to_screen_name <lgl>, is_quote <lgl>, is_retweet <lgl>,
#   favorite_count <int>, retweet_count <int>, quote_count <int>,
#   reply_count <int>, hashtags <list>, symbols <list>,
#   urls_url <list>, urls_t.co <list>, urls_expanded_url <list>,
#   media_url <list>, media_t.co <list>, …
```

And this is the problem:
``` r
> stream_tweets(token = token)
Streaming tweets for 30 seconds...
The stream disconnected prematurely. Reconnecting...
Reconnecting again...
NULL      
```

### Twitter App Settings
User authentication settings: OAuth 1.0a and OAuth 2.0 turned on.
Callback URI / Redirect URL: http://127.0.0.1:1410
App permissions: Read
Type of App: Web App

### rtweet version

``` r
> packageVersion("rtweet")
[1] ‘0.7.0’
```

### Session info

``` r
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Garuda Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C           
 [3] LC_TIME=en_US.UTF-8     LC_COLLATE=en_US.UTF-8 
 [5] LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8    LC_NAME=C              
 [9] LC_ADDRESS=C            LC_TELEPHONE=C         
[11] LC_MEASUREMENT=C        LC_IDENTIFICATION=C    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] httpuv_1.6.5    rtweet_0.7.0    lubridate_1.8.0
 [4] RSelenium_1.7.7 forcats_0.5.1   stringr_1.4.0  
 [7] dplyr_1.0.8     purrr_0.3.4     readr_2.1.2    
[10] tidyr_1.2.0     tibble_3.1.6    ggplot2_3.3.5  
[13] tidyverse_1.3.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8        binman_0.1.2      prettyunits_1.1.1
 [4] assertthat_0.2.1  utf8_1.2.2        R6_2.5.1         
 [7] cellranger_1.1.0  backports_1.4.1   reprex_2.0.1     
[10] httr_1.4.2        pillar_1.7.0      progress_1.2.2   
[13] rlang_1.0.2       curl_4.3.2        readxl_1.3.1     
[16] rstudioapi_0.13   wdman_0.2.5       bit_4.0.4        
[19] munsell_0.5.0     broom_0.8.0       compiler_4.1.3   
[22] modelr_0.1.8      pkgconfig_2.0.3   askpass_1.1      
[25] openssl_1.4.6     tidyselect_1.1.1  XML_3.99-0.8     
[28] fansi_1.0.2       crayon_1.4.2      tzdb_0.2.0       
[31] dbplyr_2.1.1      withr_2.4.3       later_1.3.0      
[34] bitops_1.0-7      grid_4.1.3        jsonlite_1.7.3   
[37] gtable_0.3.0      lifecycle_1.0.1   DBI_1.1.2        
[40] pacman_0.5.1      magrittr_2.0.3    semver_0.2.0     
[43] scales_1.1.1      cli_3.1.1         stringi_1.7.6    
[46] vroom_1.5.7       fs_1.5.2          promises_1.2.0.1 
[49] xml2_1.3.3        ellipsis_0.3.2    generics_0.1.2   
[52] vctrs_0.3.8       tools_4.1.3       bit64_4.0.5      
[55] glue_1.6.1        hms_1.1.1         parallel_4.1.3   
[58] colorspace_2.0-2  caTools_1.18.2    rvest_1.0.2      
[61] haven_2.4.3     
```

**Comment by llrs** [comment] 2022-06-01 08:40
Hi, Many thanks for the report, I think this is solved on the devel version of rtweet on this repository. If you could try it and reproduce the same error let me know. 
Be aware that there are some breaking changes on this version that will become rtweet 1.0.0 (for example the column names of all the tweets data returned by rtweet, like search_tweets, have changed)

**Comment by llrs** [comment] 2022-06-17 11:03
I'm closing the issue as I can't reproduce it, it might have been some transitory problem with the API.

**Closed by llrs** 2022-06-17 11:03 UTC
