### ISSUE TITLE
Error in get_followers for large amounts of followers

### ISSUE THREAD

**Issue by Deuana** [ropensci/rtweet#284] opened 2018-08-20 21:00 UTC
I've encountered the error even if the value of n for the current number of followers, the same error message is displayed.

``` pres <- get_followers("potus", n = "all",  retryonratelimit = TRUE)
75000 followers!
Waiting about 13.1 minutes for rate limit reset...
Waiting about -0.2 minutes for rate limit reset...
Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) : 
  invalid 'time' value
```

**Comment by llrs** [comment] 2021-02-15 21:23
Duplicate of #277

**Closed by llrs** 2021-02-15 21:23 UTC
