### ISSUE TITLE
Tweetshot risks being obsoleted by Twitter December 2020

### ISSUE THREAD

**Issue by ikohane** [ropensci/rtweet#458] opened 2020-11-29 15:22 UTC
### Problem
Was using tweetshot to retrieve a tweet image linked to a specific status_id and I get a warning within an RStudio window that says "This is a legacy version of twitter.com. We will be shutting it down on 15 December 2020. Please switch to a supported browser..."

### Reproduce the problem

``` r
tweet_shot('1333063129262067715', zoom = 3, scale = TRUE)

```

### rtweet version

``` r
## copy/paste output
‘0.7.0’
```

### Session info

``` r
## copy/paste output
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] webshot_0.5.2   magick_2.5.2    forcats_0.5.0   stringr_1.4.0   dplyr_1.0.0     purrr_0.3.4     readr_1.3.1     tidyr_1.1.0    
 [9] tibble_3.0.3    ggplot2_3.3.2   tidyverse_1.3.0 rtweet_0.7.0   

loaded via a namespace (and not attached):
 [1] progress_1.2.2    tidyselect_1.1.0  haven_2.3.1       colorspace_1.4-1  vctrs_0.3.1       generics_0.0.2    utf8_1.1.4       
 [8] blob_1.2.1        rlang_0.4.7       pillar_1.4.6      glue_1.4.1        withr_2.2.0       DBI_1.1.0         dbplyr_1.4.4     
[15] modelr_0.1.8      readxl_1.3.1      lifecycle_0.2.0   munsell_0.5.0     gtable_0.3.0      cellranger_1.1.0  rvest_0.3.5      
[22] labeling_0.3      callr_3.4.3       ps_1.3.3          curl_4.3          fansi_0.4.1       broom_0.7.0       Rcpp_1.0.5       
[29] openssl_1.4.2     scales_1.1.1      backports_1.1.8   jsonlite_1.7.0    farver_2.0.3      fs_1.4.2          hms_0.5.3        
[36] askpass_1.1       digest_0.6.25     stringi_1.4.6     processx_3.4.3    grid_4.0.2        cli_2.0.2         tools_4.0.2      
[43] magrittr_1.5      crayon_1.3.4      pkgconfig_2.0.3   ellipsis_0.3.1    xml2_1.3.2        prettyunits_1.1.1 reprex_0.3.0     
[50] lubridate_1.7.9   assertthat_0.2.1  httr_1.4.1        rstudioapi_0.11   R6_2.4.1          compiler_4.0.2   
```

### Token

``` r
## copy/paste output
rtweet::get_token()
```

**Comment by llrs** [comment] 2020-12-22 11:59
Couldn't reproduce the warning message on rtweet (0.7.0) on R 4.0.1 (both on Rstudio 1.4 preview and just R terminal): 

```
> ts=tweet_shot('1333063129262067715', zoom = 3, scale = TRUE)
Linking to ImageMagick 6.9.10.23
Enabled features: fontconfig, freetype, fftw, lcms, pango, webp, x11
Disabled features: cairo, ghostscript, rsvg
Using 4 threads
> ts
# A tibble: 1 x 7
  format width height colorspace matte filesize density
  <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
1 PNG      787    519 sRGB       TRUE         0 28x28  
```

The only thing I noticed is that on Rstudio it opens a Viewer which reports "This browser is no longer  supported" (it seems it tries to load a webpage from twitter.

As this is on rstudio only, it is an issue it might be worth opening there.

**Comment by Arf9999** [comment] 2021-01-11 11:06
`tweet_shot` uses {webshot}, and in theory it should be possible to change the user-agent of `webshot` to the default browser, rather than Rstudio's default.

**Comment by Arf9999** [comment] 2021-01-11 13:55
> `tweet_shot` uses {webshot}, and in theory it should be possible to change the user-agent of `webshot` to the default browser, rather than Rstudio's default.

A quick and dirty modification of @mkearney's code seems to bear this out: 

```
tweet_shot2 <- function (statusid_or_url, zoom = 3, scale = TRUE) 
{
  require("rtweet")
  require("magick")
  require("webshot")
  
  as_percent <- function (x) 
  {
    paste0(round(x * 100), "%")
  }

  statusid_or_url <- statusid_or_url[1]
  zoom <- zoom[1]
  scale <- scale[1]
  if (zoom <= 1) {
    stop("zoom must be a positive number, >= 1", call. = FALSE)
  }
  if (!is.logical(scale)) {
    stop("scale must be TRUE/FALSE", call. = FALSE)
  }
  x <- statusid_or_url
  is_url <- grepl("^http[s]://", x)
  if (is_url) {
    is_twitter <- grepl("twitter", x)
    if (!is_twitter) {
      stop("statusid_or_url must be a valid Twitter status id or URL", 
           call. = FALSE)
    }
    is_status <- grepl("status", x)
    if (!is_status) {
      stop("statusid_or_url must be a valid Twitter status id or URL", 
           call. = FALSE)
    }
    already_mobile <- grepl("://mobile\\.", x)
    if (!already_mobile) {
      x <- sub("://twi", "://mobile.twi", x)
    }
  }
  else {
    x <- rtweet::lookup_tweets(x)
    if (!(nrow(x) > 0)) {
      stop("Twitter status not found", call. = FALSE)
    }
    x <- sprintf("https://mobile.twitter.com/%s/status/%s", 
                 x$screen_name, x$status_id)
  }
  tf <- tempfile(fileext = ".png")
  on.exit(unlink(tf), add = TRUE)
  webshot::webshot(url = x, file = tf, zoom = zoom, useragent ="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36")
  img <- magick::image_read(tf)
  img <- magick::image_trim(img)
  if ((zoom > 1) && (scale)) {
    img <- magick::image_scale(img, as_percent(1/zoom))
  }
  img
}
```
The above function uses a Chrome browser useragent.

Using the OP's request with the new function:
```
> tweet_shot2('1333063129262067715', zoom = 3, scale = TRUE)
# A tibble: 1 x 7
  format width height colorspace matte filesize density
  <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
1 PNG      982    724 sRGB       TRUE         0 28x28 

```

![image](https://user-images.githubusercontent.com/36820513/104190509-e146c700-5424-11eb-9cae-6d208f05ec98.png)

**Comment by llrs** [comment] 2021-02-18 17:40
Not sure this should be fixed here or in webshot, which hasn't had activity in over 1 year, and the author sometimes [recommends](https://github.com/wch/webshot/issues/96#issuecomment-642967480) another package [webshot2](https://github.com/rstudio/webshot2/).

**Comment by hadley** [comment] 2021-02-27 13:19
Yeah, this should be resolved by switching to webshot2 (once it's available)

**Comment by llrs** [comment] 2021-11-18 22:12
I forgot to tweak the code to generate the right url when tweet_shot is given a tweet id. I added a couple more of tests to avoid this oversight on the future. However, the image I see at the end is 
![Screenshot from 2021-11-18 22-27-29](https://user-images.githubusercontent.com/6818218/142502779-f48f6ce3-0b0a-4a5d-9200-67551b20065b.png)
I tried with @Arf9999 user agent but it didn't work (and even if it did it would probably break often). Not sure if it is used much or not .

**Comment by llrs** [comment] 2022-05-06 10:57
I deprecated the function, waiting for webshot or webshot2 to work in the future.

**Comment by llrs** [comment] 2022-05-23 07:51
webshot2 is now on CRAN, if it works it could replace webshot.

**Comment by llrs** [comment] 2022-05-24 21:56
Couldn't find a way to use webshot2 to capture only the tweet, the selector is not enough to hide the cookies banners blocking the view of the content. 
Check branch webshot2 for the code, but the relevant piece is this:

```r
  x <- "https://mobile.twitter.com/ma_salmon/status/947061504892919808"
  webshot2::webshot(url = x,  
                    selector = c('article[data-testid="tweet"]'),
                    delay = 0.5) # Give some time to load the content
```

If anyone finds a good selector please let me know

**Comment by schloerke** [comment] 2022-05-28 01:05
Here's at least something using `{chromote}`. I had to overwrite the user agent so that twitter didn't redirect the url. I used my local Chrome agent.  The selector may not be perfect, but it is closer!

```r
x <- "https://mobile.twitter.com/ma_salmon/status/947061504892919808"
filename <- "tweetshot.png"

# Open session
b <- chromote::ChromoteSession$new()
# Override User agent
b$Emulation$setUserAgentOverride("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36")

# Go to page
b$Page$navigate(x)
# Wait until page has load event fired
b$Page$loadEventFired()
# Wait for page to load more things
Sys.sleep(1) 
# Take screenshot
b$screenshot(
  filename = filename, 
  selector = "div[data-testid='primaryColumn'] div[data-testid='cellInnerDiv']:first-of-type article[data-testid='tweet']:first-of-type", 
  delay = 0
)
b$close()
```

File:
![tweetshot](https://user-images.githubusercontent.com/93231/170803629-f55c9d45-4e39-405b-af02-f5394814a0f2.png)

**Comment by llrs** [comment] 2022-05-28 09:54
Many thanks, it works well as independent, but when I add it to the package source code it does not longer save the image. Also it seems that it generates spurious warnings and errors even with the exact same code such as :

```
Error: Chromote: timed out waiting for event Page.loadEventFired
Warning message:
In onRejected(reason) :
    An error occurred: Error in onFulfilled(value): Unable to find any visible elements for selectors.
```

Probably this is due to Twitter or the connection, but it doesn't seem reliable enough to provide it to the users so I think it will be better to leave `tweet_shot` deprecated.

**Comment by schloerke** [comment] 2022-05-28 15:12
I'ma give it another shot to have a dynamic wait time...

**Comment by schloerke** [comment] 2022-05-28 16:41
Ok. More code, but should be MUCH more robust...

`screenshot_delayed_selector`: Does not depend on promises. Runs code synchronously.
`screenshot_delayed_selector_async`: Depends on promises. Runs code synchronously or asynchronously.

Examples are given at the end.  

If you have no intent on using promises, `screenshot_delayed_selector()` is sufficient and is much easier to debug. 😄 

```r
library(promises)


screenshot_delayed_selector <- function(
  url,
  selector,
  filename = NULL,
  user_agent = NULL,
  timeout = 10 * 1000,
  delay = 0
) {
  b <- chromote::ChromoteSession$new()
  if (!is.null(user_agent)) b$Network$setUserAgentOverride(user_agent)
  b$Page$navigate(url)
  b$Page$loadEventFired()

  json_stringify <- function(x, ..., auto_unbox = TRUE) {
    jsonlite::toJSON(x, ..., auto_unbox = auto_unbox)
  }
  b$Runtime$evaluate(
    awaitPromise = TRUE,
    returnByValue = FALSE,
    paste0("
    new Promise((resolve, reject) => {
      const timeout = ", json_stringify(as.numeric(timeout)[1]), ";
      const selector = ", json_stringify(as.character(selector)[1]), ";

      function check_dom() {
        const element = document.querySelector(selector);
        if (element) {
          // Done!
          resolve(element);
        } else {
          // Try again 10 ms later
          setTimeout(check_dom, 10);
        }
      }
      check_dom();
    })
    ")
  )
  b$screenshot(filename = filename, selector = selector, delay = delay, show = is.null(filename))
  b$close()
}



screenshot_delayed_selector_async <- function(
  url,
  selector = "html",
  filename = NULL,
  user_agent = NULL,
  timeout = 10 * 1000,
  delay = 0,
  wait_ = TRUE
) {
  json_stringify <- function(x, ..., auto_unbox = TRUE) {
    jsonlite::toJSON(x, ..., auto_unbox = auto_unbox)
  }

  b <- chromote::ChromoteSession$new()
  if (!is.null(user_agent)) {
    b$Network$setUserAgentOverride(user_agent, wait = TRUE)
  }

  p <-
    { b$Page$navigate(url, wait_ = FALSE) } %...>%
    { b$Page$loadEventFired(wait_ = FALSE) } %...>%
    # Wait until the selector is there
    {
      b$Runtime$evaluate(
        wait_ = FALSE,
        timeout = 2 * timeout,
        awaitPromise = TRUE,
        returnByValue = FALSE,
        paste0("
        new Promise((resolve, reject) => {
          const timeout = ", json_stringify(as.numeric(timeout)[1]), ";
          const end = Date.now() + timeout;
          const selector = ", json_stringify(as.character(selector)[1]), ";

          function check_dom() {
            const element = document.querySelector(selector);
            if (element) {
              // Done!
              resolve(element);
              return;
            }

            if (Date.now() > end) {
              throw 'Timeout waiting for element';
            }
            // Try again 10 ms later
            setTimeout(check_dom, 10);
          }
          check_dom();
        })
        ")
      )
    } %...>%
    {
      b$screenshot(
        filename = filename,
        selector = selector,
        delay = delay,
        show = is.null(filename),
        wait_ = FALSE
      )
    }
  p$finally(function() {
    b$close(wait_ = FALSE)
  })

  # Return the value or
  if (wait_) {
    b$wait_for(p)
  } else {
    p
  }
}


user_agent <- "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
selector <- "div[data-testid='primaryColumn'] div[data-testid='cellInnerDiv']:first-of-type article[data-testid='tweet']:first-of-type"


url <- "https://twitter.com/ma_salmon/status/947061504892919808"

message("sync start")
screenshot_delayed_selector(url, selector, filename = "rtweet-sync.png", user_agent = user_agent)
message("sync done")


message("async (but sync) start")
screenshot_delayed_selector_async(url, selector, filename = "rtweet-sync2.png", user_agent = user_agent, wait = TRUE)
message("async (but sync) done")


message("async start")
p <- screenshot_delayed_selector_async(url, selector, filename = "rtweet-async.png", user_agent = user_agent, wait = FALSE)
p$then(function(value) {
  message("async done: ", value)
})


proms <- lapply(sample(c(
  "https://twitter.com/ma_salmon/status/947061504892919808",
  "https://twitter.com/schloerke/status/1530276662692175874",
  "https://twitter.com/aRtsy_package/status/1530432933130997760"
)), function(url) {
  filename <- paste0(strsplit(url, "/")[[1]][[4]], ".png")
  message("starting file: ", filename)
  p <- screenshot_delayed_selector_async(url, selector, filename = filename, user_agent = user_agent, wait = FALSE)
  p$then(function(value) {
    message("finished file: ", filename)
    value
  })
})

prom <- promises::promise_all(.list = proms)
prom$then(function(value) {
  message("done")
})
```


<img width="1042" alt="Screen Shot 2022-05-28 at 12 39 44 PM" src="https://user-images.githubusercontent.com/93231/170834615-9b23e5f6-4cea-4d65-95dd-1581a78ad9a9.png">

**Comment by llrs** [comment] 2022-05-28 17:13
There is too much code I don't understand that I don't feel confident I could maintain the functionality when Twitter changes the interface or whatever other problem might arise. In addition, the number of dependencies makes me uncomfortable and that it only works for chrome based browsers too... 

Thanks for all the help.

**Closed** 2022-06-02 17:16 UTC
Labels: bug
