### ISSUE TITLE
Cannot stream tweets

### ISSUE THREAD

**Issue by 7Sis** [ropensci/rtweet#404] opened 2020-03-22 11:12 UTC
Hey,

for me both the functions stream_tweets and stream_tweets2 do not work.

Problem with stream_tweets:

> Streaming tweets for 10 seconds...
The stream disconnected prematurely. Reconnecting...
Reconnecting again...
streaming data saved as 1.json

My code:

> test <- stream_tweets(q= "test", parse = FALSE, file_name = "1", timeout = 10)

Problem with stream_tweets2:

The folder in which the data is saved is automatically deleted at the end of the data collection.

Hence, currently I cannot stream tweets at all. I know that other people have experienced these issues and was wondering whether there are any current solutions. 

In addition, I have also experienced problems with the Rest API. Here, the retryonratelimit does not work and will give me an error message as well...

> retry on rate limit...
waiting about -50 minutes...
error in Sys.sleep(reset + 2) : invalid time value

I am authenticated and have installed the newest version of rtweet (0.7.0).

**Comment by Bisaloo** [comment] 2020-05-10 19:23
I have the same issue:

> Error in Sys.sleep(reset + 2) : invalid 'time' value

I checked and it's because `reset < -2` so `reset + 2 < 0`

**Comment by TKMSc** [comment] 2020-11-04 15:14
Hey @7Sis, I'm having exactly the same two problems. Did you ever figure out a solution?

**Comment by llrs** [comment] 2020-12-22 12:10
Cannot reproduce the errors on 0.7.0 on R 4.0.1. But with stream_tweets2 I don't see the file.
Seems and error on the logic at the end of the function as currently implemented

**Comment by llrs** [comment] 2021-02-17 21:46
The stream_tweets2 deletion is fixed by #472 once it gets merged. Closing now as I cannot reproduce the first error message

**Closed by llrs** 2021-02-17 21:46 UTC
