### ISSUE TITLE
maxResults parameter in rtweets set to 100 default

### ISSUE THREAD

**Issue by Shooony** [ropensci/rtweet#383] opened 2020-01-17 03:20 UTC
https://github.com/ropensci/rtweet/blob/f9cada85b60101abce14c19afb8c4707202ad699/R/search_tweets.R#L403

Twitter premium now allows up to 500 per request. I think this should be modified.

**Comment by zach-wildfig** [comment] 2020-02-02 22:56
This actually ends up causing a lot of issues if you have a premium application. If you end up wanting to retrieve 500, it costs you 5 calls in your API limit, which when working over larger data sets can exhaust your API limit 5x faster than you anticipated.

**Comment by biffpm** [comment] 2020-03-12 21:55
Hello - Is there any solution to this other than using a package other than rtweet? Is there any manual way to change how the pagination occurs?

**Comment by norcalbiostat** [comment] 2020-04-19 20:30
This problem was identified in #347. @kevintaylor created a PR that was never included. 
I've been using his forked version of the package :https://github.com/ropensci/rtweet/issues/347#issuecomment-565150988 
and it correctly only uses 1 API call per block of 500.

**Comment by llrs** [comment] 2021-02-16 23:12
Closing as duplicate of #317, #347 and #368, which are fixed once #375 gets merged.

**Closed by llrs** 2021-02-16 23:12 UTC
