### ISSUE TITLE
Problems with streaming tweets

### ISSUE THREAD

**Issue by LuigiC72** [ropensci/rtweet#659] opened 2022-03-12 08:56 UTC
Goodmorning,
since a couple of days I have the same two issues when using the stream_tweets function. 

If I run an empty search (i.e., stream_tweets("", timeout = 10)) I get the following error:  
Authentication complete.
Streaming tweets for 10 seconds...
Finished streaming tweets!                                                                                                                   
Error: parse error: unallowed token at this point in JSON text
          stamp_ms":"1647074468665"},  ,  {"created_at":"Sat Mar 12 08
                     (right here) ------^

If on the other hand I run the stream_tweets function with a query (i.e., stream_tweets("trump", timeout = 10)) or a geocode (i.e.,  stream_tweets(lookup_coords("USA", apikey=api),timeout = 30)) I am able to stream the tweets. However I also get the following error: 
In file.remove(file_name) :
  cannot remove file 'stream-20220312094652.json', reason 'Permission denied'

Any reasons why for both issues?
Thanks!
Luigi

**Comment by llrs** [comment] 2022-03-12 09:20
Which version of rtweet and R are you using? What have you tried to solve this? Could you report the traceback() after these errors? Are you sure you have the right authentication to access the stream endpoint (and you haven't hit any penalty or timelimit)?

**Comment by LuigiC72** [comment] 2022-03-12 09:39
rtweet_0.7.0, R version 4.1.0 (same problem if using Rstdudio 2022.02.0 Build 443 ). I haven't hit any penaly of any sort (I suppose) given that I have no problems with the search_tweet function. 

This is the traceback of the error:
> dt <- stream_tweets("", timeout = 10)
Streaming tweets for 10 seconds...
Finished streaming tweets!
                                                                                                                   
Error: parse error: unallowed token at this point in JSON text
          stamp_ms":"1647077297662"},  , {"created_at":"Sat Mar 12 09:
                     (right here) ------^
>  traceback() 
9: parse_string(txt, bigint_as_char)
8: parseJSON(txt, bigint_as_char)
7: parse_and_simplify(txt = txt, simplifyVector = simplifyVector, 
       simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, 
       flatten = flatten, ...)
6: jsonlite::fromJSON(d)
5: .parse_stream_two(d)
4: data_from_stream2("stream-20220312102821.json", verbose = TRUE)
3: do.call("data_from_stream2", c(path, dots))
2: parse_stream(file_name, verbose = verbose)
1: stream_tweets("", timeout = 10)

In the case of the SECOND error I have just this weird warning each time:
dt <- stream_tweets("trump", timeout = 10)
Streaming tweets for 10 seconds...
Finished streaming tweets!                                                                                                        
Warning message:
In file.remove(file_name) :
  cannot remove file 'stream-20220312103611.json', reason 'Permission denied'

Thanks!

**Comment by llrs** [comment] 2022-03-12 09:51
Please, check that you really didn't hit a limit via `rate_limit("/tweets/search/stream")`. The restrictions Twitter sets are for each endpoint (for example, you could search tweet but not post tweets).  
If this is not the case it could be that Twitter is returning an incorrect formatted json (it has happened before) and has nothing to do with rtweet.

**Comment by LuigiC72** [comment] 2022-03-12 10:38
Here the results via rate_limit("/tweets/search/stream"). It does not seem that I have hit any limit. Isn't it? Is there any way to deal with it then? And more in general, if you run this query, do you have the same error? 
Thanks

# A tibble: 262 x 7
   query limit remaining reset   reset_at timestamp app  
   <chr> <int>     <int> <drtn>  <dttm>   <dttm>    <chr>
 1 <NA>     NA        NA NA mins NA       NA        <NA> 
 2 <NA>     NA        NA NA mins NA       NA        <NA> 
 3 <NA>     NA        NA NA mins NA       NA        <NA> 
 4 <NA>     NA        NA NA mins NA       NA        <NA> 
 5 <NA>     NA        NA NA mins NA       NA        <NA> 
 6 <NA>     NA        NA NA mins NA       NA        <NA> 
 7 <NA>     NA        NA NA mins NA       NA        <NA> 
 8 <NA>     NA        NA NA mins NA       NA        <NA> 
 9 <NA>     NA        NA NA mins NA       NA        <NA> 
10 <NA>     NA        NA NA mins NA       NA        <NA>

**Comment by llrs** [comment] 2022-03-12 11:08
When I run your examples I do not get the same error messages. 

Sorry, I forgot that you are using the CRAN version, you'll need to manually explore the result of r`ate_limit()` to find if the endpoints related to stream hit the limit. Good luck!

I'm closing the issue because I don' think this is rtweet fault. If you have some evidence that the problem is with rtweet you can explain it in a new comment.

**Closed by llrs** 2022-03-12 11:08 UTC

**Comment by resulumit** [comment] 2022-03-12 13:18
This is likely to be related to known bug in the CRAN version (see, for example, https://github.com/ropensci/rtweet/issues/630), related to parsing data. 

One can still collect data via streaming, but often (but not always --- depending on the returned data. In other words, sometimes it works) cannot turn the list of lists (returned by API) into a data frame.

For example, the following will work, and the data will be saved as .json into the working directory (because `parse = FALSE`):

````
stream_tweets(q ="", timeout = 10, parse = FALSE))

````

**Comment by llrs** [comment] 2022-03-12 14:21
Could be, but if this is the case it is already solved on the development version.

**Comment by resulumit** [comment] 2022-03-12 15:27
Yes. Many users of this package are unaware of the fact that the CRAN version hasn't been updated for years, and the development version is very much different, and many problems have already been fixed in the development version. 

Perhaps you could make this clearer in the landing page on GitHub, and on the issue page one could pin a message at the top. I think this would save you asking "what version are you using" as your first answer to every issue/question.
